### ISSUE TITLE
[@triniwiz/nativescript-image-cache-it] Build fails after updating XCode to 14.3

### ISSUE THREAD

**Issue by VepretskiyD** [triniwiz/nativescript-plugins#176]
```
...
1 warning generated.
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/SDWebImage-umbrella.h"
        ^
/Users/dmytrovepretskyi/Desktop/seesnap-2/nativescript-app/platforms/ios/build/Debug-iphonesimulator/SDWebImage/SDWebImage.framework/Headers/SDWebImage-umbrella.h:57:9: note: in file included from /Users/dmytrovepretskyi/Desktop/seesnap-2/nativescript-app/platforms/ios/build/Debug-iphonesimulator/SDWebImage/SDWebImage.framework/Headers/SDWebImage-umbrella.h:57:
#import "SDWebImagePrefetcher.h"
        ^
/Users/dmytrovepretskyi/Desktop/seesnap-2/nativescript-app/platforms/ios/build/Debug-iphonesimulator/SDWebImage/SDWebImage.framework/Headers/SDWebImagePrefetcher.h:92:1: error: property with 'retain (or strong)' attribute must be of object type
@property (strong, nonatomic, nonnull) dispatch_queue_t delegateQueue;
^
/Users/dmytrovepretskyi/Desktop/seesnap-2/nativescript-app/node_modules/@triniwiz/nativescript-image-cache-it/platforms/ios/src/ImageCacheItUtils.swift:10:8: error: could not build Objective-C module 'SDWebImage'
import SDWebImage
       ^
...
** BUILD FAILED **

Unable to apply changes on device: 39EDFAD2-BE45-4EA6-BCC5-5AEA734A5DA6. Error is: Command xcodebuild failed with exit code 65.
```

Same thing if I try to build in XCode
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/17052346/230972504-c17056bd-1539-4a27-9e41-9b0f2eafb1d4.png">

<img width="1526" alt="image" src="https://user-images.githubusercontent.com/17052346/230972344-006e71aa-1a42-4f93-adc1-a068bd569179.png">

I updated the `"@triniwiz/nativescript-image-cache-it"` plugin to the latest 7.3.0

`ns doctor` returns this:

```
No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 14.3.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 8.4.0 and the latest available version is 8.5.2.
✔ Component @nativescript/core has 8.5.0 version and is up to date.
✔ Component @nativescript/ios has 8.5.1 version and is up to date.
✔ Component @nativescript/android has 8.5.0 version and is up to date.
```

Before the XCode update, everything was working perfectly fine

**Comment by VepretskiyD** [comment]
After updating the NativeScript CLI to 8.5.3 I was able to build for iOS. This issue can be closed. Thanks, @edusperoni !
